# CodeRabbit Configuration for Framework LED Matrix Daemon
# https://docs.coderabbit.ai/reference/configuration

# Language-specific settings
language: "en-US"

# Tone and communication style - global setting per schema
tone_instructions: "Use a constructive tone with comprehensive analysis focused on Go best practices, hardware safety, and system programming patterns."

# Review settings
reviews:
  # Auto-review settings
  auto_review:
    enabled: true

  # When enabled, CodeRabbit will approve once comments are resolved and checks are green
  request_changes_workflow: true
  # High-level summary settings
  high_level_summary: true
  
  # Auto-generate PR titles based on changes
  auto_title_instructions: |
    Generate a concise PR title following conventional commit format:
    - Use prefixes: feat, fix, perf, refactor, docs, test, ci, chore
    - Focus on the primary change or feature being added
    - Keep under 60 characters
    - Be specific about the component affected (e.g., "logging", "metrics", "ci")
    
    Examples:
    - "feat: add structured logging with slog integration" 
    - "perf: optimize metrics collection performance"
    - "ci: add automated release workflow with cross-platform builds"
    - "fix: resolve configuration validation edge cases"
  
  # Poem style for summaries (fun touch)
  poem: true

  path_filters:
    - "!**/go.sum"
    - "!**/LICENSE"
    - "!**/.gitignore"

  # Path-based review settings
  path_instructions:
    - path: "**/*_test.go"
      instructions: |
        For test files, focus on:
        - Test completeness and edge case coverage
        - Proper use of testify or standard testing patterns
        - Table-driven tests where appropriate
        - Proper setup and teardown
        - Mock usage and test isolation
        - Go idioms and best practices
        - Proper error handling patterns

    - path: "internal/matrix/**"
      instructions: |
        For matrix package, focus on:
        - Hardware communication safety (Framework LED protocol compliance)
        - Proper error handling for serial operations
        - Resource cleanup with defer statements
        - Thread safety for concurrent access
        - Efficient goroutine and channel usage
        - Proper synchronization to avoid race conditions

    - path: "internal/config/**"
      instructions: |
        For config package, focus on:
        - Validation logic completeness
        - Error message clarity
        - Default value appropriateness
        - Security of configuration handling (no secrets exposure)
        - Input validation and sanitization
        - Proper struct design and interface usage

    - path: "internal/stats/**"
      instructions: |
        For stats package, focus on:
        - Accuracy of system statistics collection
        - Performance impact and memory efficiency
        - Cross-platform compatibility
        - Proper error handling for system calls
        - Avoiding memory leaks in collection routines

    - path: "cmd/**"
      instructions: |
        For command-line interfaces, focus on:
        - User experience and clear error messages
        - Flag and argument validation
        - Help text clarity
        - Exit code conventions
        - Proper CLI patterns and best practices

  # Enable Go-specific linting and analysis tools
  tools:
    golangci-lint:
      enabled: true

    shellcheck:
      enabled: true

    markdownlint:
      enabled: true

    github-checks:
      enabled: true
      timeout_ms: 90000