# GolangCI-Lint Configuration for Framework LED Matrix Daemon
# https://golangci-lint.run/usage/configuration/

# Configuration version
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional quality linters
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - copyloopvar
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - usetesting
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5

  settings:
    # Cyclomatic complexity
    cyclop:
      max-complexity: 60
      package-average: 10.0

    # Function length
    funlen:
      lines: 300
      statements: 100

    # Cognitive complexity
    gocognit:
      min-complexity: 60

    # Cyclomatic complexity (alternative)
    gocyclo:
      min-complexity: 60

    # Line length
    lll:
      line-length: 120

    # Struct tag validation
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    # Security analysis
    gosec:
      severity: "low"
      confidence: "low"
      excludes:
        - G204 # Subprocess launched with variable - acceptable for daemon operations

    # Naming conventions
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "disableStutteringCheck"
        - name: package-comments
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - ["ID"] # Allow ID in variable names

    # Error handling
    errcheck:
      check-type-assertions: true
      check-blank: true

    # Unused parameters
    unparam:
      check-exported: false

    # Unused variables/constants
    unused:
      exported-fields-are-used: false

    # Whitespace
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
          - gocognit

      # Exclude shadow checking in test files  
      - path: '_test\.go'
        text: "shadow"
        linters:
          - govet

      # Exclude package comment requirement for main package
      - path: 'cmd/'
        text: "package-comments"
        linters:
          - revive

      # Allow long lines in generated files
      - source: "^//go:generate "
        linters:
          - lll

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

  settings:
    # Import organization
    goimports:
      local-prefixes: 
        - github.com/timfallmk/framework-led-matrix-daemon

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0
